.TH sprot 1 "August 23, 2009"
.SH NAME
sprot \- The same onliner you see with the --help option
.SH SYNOPSIS
.B sprot
[
.B -v
] [
.B -h
]
.SH DESCRIPTION
The DESCRIPTION section of a manual page should contain a brief description
of what the command does, in terms that the user cares about.
.SH OPTIONS
.TP
-v,--version
This displays the version of the program. Here in the manpage there
is more room for explaining what an option does.
.TP
-h,--help
Display the commandline help and exit sucessfully.
